### PR TITLE
Optional class loader & Update options in runtime

### PR DESCRIPTION
**Pull request by ruslan-polutsygan**
Alternative to this PR https://github.com/theodo/TheodoEvolutionLegacyWrapperBundle/pull/20
and merged with this https://github.com/theodo/TheodoEvolutionLegacyWrapperBundle/pull/21

### CODE REVIEW

**Comment by ruslan-polutsygan** [comment]
Hi @benja-M-1 
I decided to update 2 pull requests into one. I hope you don't mind.

**Comment by ruslan-polutsygan** [comment]
Hello @benja-M-1 

What do you think about this pull request? Are you going to review and/or merge it?
Let me know please.

Thanks

**Comment by benja-M-1** [comment]
Hi @ruslan-polutsygan thanks for the PR. I do prefer small PRs but that's fine :)

I'll review later, I can't do it right now.But from what I saw it seems promising. I'll try to do it at the end of the day (Paris time).

Thanks again for your work !

**Comment by ruslan-polutsygan** [comment]
hi
I was just wondering whether it's OK in general or I should continue working with my own fork.
I'm not rushing you. Today - is great  :)

**Comment by benja-M-1** [comment]
In general it's OK :) I do prefer to make the autoload service optional rather than to add an empty class as in #20.

**Comment by benja-M-1** [comment]
Hi @ruslan-polutsygan, I tester your PR and it seems working perfectly! :cake: 

Thank you for your contribution, I merge your PR.

**Comment by ruslan-polutsygan** [comment]
hi @benja-M-1 
That's awesome :)

**Pull request merged**
