### PR TITLE
Added support for symfony 3.0

### PR DESCRIPTION
**Pull request by partikus**

### CODE REVIEW

**Comment by partikus** [comment]
@benja-M-1 ping, please take a look

**Comment by xocasdashdash** [comment]
Is this all that's neede for symfony3 support?

**Comment by benja-M-1** [comment]
@partikus it seems that someone disabled the travis build. I re enabled it but I can't manually make the build run your PR, do you think that you can force push on your PR to make the build run? (Or maybe you have a better idea? :))

**Comment by benja-M-1** [comment]
@partikus thanks for your contribution, I close this PR in favor of #29 where @nicodmf went further.

**Pull request closed without merging**
